gdrplatform/gDRstyle

DESCRIPTION, R/check.R, inst/NEWS.md
downgrade version to make it Bioconductor compatible
=> chore: downgrade version to make it Bioconductor compatible

DESCRIPTION, NEWS.md
See: https://gred.slack.com/archives/C028XVA7ZFF/p1680539445642929
=> chore: change location of NEWS.md && bump v+c

DESCRIPTION, LICENSE, NEWS.md
The aim of this PR is to trigger the build on the BioC: (upstream/devel branch). To do so we need a new version. Thus I've used this as the opportunity to switch to the version of the license we have in gDRcore.
=> feat: update the license

DESCRIPTION, NEWS.md
Fix for the NOTE regarding the unrecognized format of NEWS.md
=> chore: fix format in NEWS.md

DESCRIPTION, NEWS.md, R/check.R, inst/config/note.json
- handle properly BiocCheck notes with mulitple lines (notes to be ignored)
Related JIRA issue:  GDR-1944
=> Gdr 1944 3

inst/config/note.json
Updated notes
Related JIRA issue: 
To require all the examples
=> doc: update notes

.github/workflows/main.yml, DESCRIPTION, NEWS.md
=> feat: introduce CD

.github/workflows/main.yml
=> fix: minor workflow fix

.github/workflows/main.yml
=> fix: minor pipeline

.github/workflows/main.yml
=> fix: trigger CI on merge

.github/workflows/bioc-sync.yaml
=> fix: resolve shallow merge issue

.github/workflows/bioc-sync.yaml
=> fix: fix for not overwritten variables

.github/workflows/pkgdown.yaml, Dockerfile, rplatform/install_repo.R
Add GHA pipeline template for pkgdown.
It will be used by all gdrplatform packages on GitHub.
Preview: https://gdrplatform.github.io/gDRstyle
More details can be found at: https://docs.google.com/document/d/1WGW4_lOOZ73lEfVZwIWMivbyCgDTJAajxP5N8767DZY.
Related JIRA issue:  GDR-2371
Enable static webpages with documentation for all packages on GitHub.
=> Gdr 2371 2

.github/workflows/pkgdown.yaml
Improve pkgdown.yml pipeline. Support R packages that are stored as subdirectories in the repositories.
=> Gdr 2371 3

.github/workflows/pkgdown.yaml
build: change token in pkgdown GHA
=> build: change token in pkgdown GHA

DESCRIPTION, NEWS.md, tests/testthat/test-build.R
=> fix: fix bioc tests

DESCRIPTION, NEWS.md, R/build_tools.R, tests/testthat/test-build.R
=> fix: replace remotes function

DESCRIPTION, NEWS.md, R/linters_config.R, inst/config/note.json
Add "debug" to the exceptions list
=> Gdr 2331 - feat: add debug to the exceptions list

.github/workflows/pkgdown.yaml, DESCRIPTION, NEWS.md
=> fix: improve pkgdown action

DESCRIPTION, NEWS.md, inst/config/note.json
Related JIRA issue: [GDR-2844](https://jira.gene.com/jira/browse/GDR-2844)
Change was required due to failing test for gDRinternal
=> [GDR-2844] update notes.json
